# Generated by Django 4.2.6 on 2023-10-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_at',
            field=models.DateField(verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='description',
            field=models.CharField(blank=True, max_length=512, verbose_name='Описание дохода'),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название дохода'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='created_at',
            field=models.DateField(verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='description',
            field=models.CharField(max_length=512, verbose_name='Описание расхода'),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название расхода'),
        ),
    ]
