# Generated by Django 4.2.6 on 2023-10-11 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0002_alter_balance_created_at_alter_income_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Дата записи')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Семья')),
            ],
            options={
                'verbose_name': 'План расходов',
                'verbose_name_plural': 'Планы расходов',
            },
        ),
        migrations.AlterField(
            model_name='balance',
            name='created_at',
            field=models.DateField(verbose_name='Дата записи'),
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма трат')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.spendingcategory')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.plan')),
            ],
            options={
                'verbose_name': 'Элемент плана расходов',
                'verbose_name_plural': 'Элементы плана расходов',
            },
        ),
    ]
