# Generated by Django 4.2.6 on 2023-10-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_plan_alter_balance_created_at_planitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecategory',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название дохода'),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название расхода'),
        ),
    ]
