# Generated by Django 4.2.6 on 2023-10-22 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0004_alter_incomecategory_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incomecategory',
            unique_together={('family', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='spendingcategory',
            unique_together={('family', 'title')},
        ),
    ]
