# Generated by Django 4.2.6 on 2023-10-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_incomecategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма'),
        ),
    ]
