# Generated by Django 4.2.6 on 2023-10-26 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0007_alter_balance_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма расходов')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Дата записи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.spendingcategory', verbose_name='Категория расходов')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Семья')),
            ],
            options={
                'verbose_name': 'План расходов',
                'verbose_name_plural': 'Планы расходов',
            },
        ),
        migrations.RemoveField(
            model_name='planitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='planitem',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PlanItem',
        ),
    ]
